---
title: "Code of Conduct"
description: |
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Our Standards

The Measuring Psychology community and study group is dedicated to providing a positive experience for everyone, regardless of:

- Age
- body size
- caste
- citizenship
- disability
- education
- ethnicity
- familial status
- gender expression
- gender identity
- genetic information
- immigration status
- level of experience
- nationality
- personal appearance
- pregnancy
- race
- religion
- sex characteristics
- sexual orientation
- sexual identity
- socio-economic status
- tribe
- veteran status

## Community Guidelines for Slack and Study group

1. Be empathetic, friendly, and respectiful. Don’t shame your peers! There are no stupid questions. We are here to learn together, so be kind.

2. Any form of prejudice or discrimination will not be allowed. This will result in immediate exclusion from the group. The administrators care about a safe environment, anyone that is suffering from it in our community, feel free to reach out to the administrators (Rafael Bastos and Marwin Carmo).

3. Be open to learning from others and teaching others.

## Inappropriate Behavior

Community members asked to stop any inappropriate behavior are expected to comply immediately.

We want all participants in the Measuring Psychology community to have the best possible experience they can. In order to be clear what that means, we've provided a list of examples of behaviors that are inappropriate for Measuring Psychology community spaces:

1.	Deliberate intimidation, stalking, or following.
2.	Sustained disruption of online discussion, talks, or other events. Sustained disruption of events, online discussions, or meetings, including talks and presentations, will not be tolerated. This includes 'Talking over' or 'heckling' event speakers or influencing crowd actions that cause hostility in event sessions. Sustained disruption also includes drinking alcohol to excess or using recreational drugs to excess, or pushing others to do so.
3.	Harassment of people who don't drink alcohol or other legal substances. We do not tolerate derogatory comments about those who abstain from alcohol or other legal substances. We do not tolerate pushing people to drink, talking about their abstinence or preferences to others, or pressuring them to drink - physically or through jeering.
4.	Sexist, racist, homophobic, transphobic, ableist language or otherwise exclusionary language. This includes deliberately referring to someone by a gender that they do not identify with, and/or questioning the legitimacy of an individual's gender identity. If you're unsure if a word is derogatory, don't use it. This also includes repeated subtle and/or indirect discrimination.
5.	Unwelcome sexual attention or behavior that contributes to a sexualized environment. This includes sexualized comments, jokes or imagery in interactions, communications or presentation materials, as well as inappropriate touching, groping, or sexual advances. Sponsors should not use sexualized images, activities, or other material. Meetup organizing staff and other volunteer organizers should not use sexualized clothing/uniforms/costumes, or otherwise create a sexualized environment.
6.	Violence or threats of violence. Violence and threats of violence are not acceptable - online or offline. This includes incitement of violence toward any individual, including encouraging a person to commit self-harm. This also includes posting or threatening to post other people's personally identifying information ("doxxing") online.
7.	Influencing or encouraging inappropriate behavior. If you influence or encourage another person to violate the Code of Conduct, you may face the same consequences as if you had violated the Code of Conduct.

## Procedure for Handling Incidents

### Reporting to administrators

If you believe someone has violated our Code of Conduct, we encourage you to report it. If you are unsure whether the incident is a violation, or whether the space where it happened is covered by this Code of Conduct, we encourage you to still report it. We are fine with receiving reports where we decide to take no action for the sake of creating a safer community.

You can make a report by sending a direct message or emailing Rafael Bastos (rafavsbastos@gmail.com) or Marwin Carmo (marwinbr@gmail.com).

a. Some guidelines to report data:

If you make a report via email or direct message, we hope you can provide us with some information that will help us identify the reported person. If you don’t remember all the details, we still encourage you to make a report. We encourage you to include the following information in your report:

- Your contact info (so we can get in touch with you if we need to follow up)
- Date of the incident
- Whether the incident is ongoing
- Which online community and which part of the online community space it occurred in
- Description of the incident
- Identifying information of the reported person such as name, online username, handle, email address.
- Any logs or screenshots of the conversation or behavior.
- Additional circumstances surrounding the incident
- Other people involved in or (if applicable) witnesses to the incident and their contact information or description.

b. Confidentiality:

All reports will be kept confidential. When the committee members discuss incidents with people who are reported, we will anonymize details as much as we can to protect reporter privacy.

However, some incidents happen in one-on-one interactions, and even if the details are anonymized, the reported person may be able to guess who made the report. If you have concerns about retaliation or your personal safety, please note those in your report. We still encourage you to report, so that we can support you while keeping our community members safe. In some cases, we can compile several anonymized reports into a pattern of behavior, and take action on that pattern.

In some cases we may determine that a public statement will need to be made. If that's the case, the identities of all people impacted by the behavior and the people who reported that behavior will remain confidential, unless those individuals instruct us otherwise.

The committee provides transparency reports about the incidents that occurred. Anonymized information from the incident you report may be included in transparency reports.

c. Conflicts of Interest:

If a committee member has a conflict of interest for a report, they will recuse themselves from the discussion and handling of the incident. The incident documentation will not be available to them, and they will excuse themselves from any conversations involving handling the incident.

d. Following Up With Reporters:

After the incident report, the committee will follow up with the person who made the report. The follow up may include:

- An acknowledgment that the administrators discussed the situation.
- Whether or not the report was determined to be a violation of the Code of Conduct.
- What actions (if any) were taken to correct the reported behavior 
